name: HeadHunters
main: no.runsafe.headhunters.Plugin
version: 1.0.42b
authors: [Naxanria]
depend: []
description:
commands:
  headhunters:
    description: Control the headhunters plugin.
    aliases: [hh]
