name: HeadHunters
main: no.runsafe.headhunters.Plugin
version: 1.0.99b
authors: [Naxanria]
depend: [RunsafeWorldGuardBridge]
description:
commands:
  headhunters:
    description: Control the headhunters plugin.
    aliases: [hh]
